# Generated by Django 2.0.5 on 2018-12-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created', models.DateField(auto_now=True, verbose_name='Создано')),
                ('term', models.DateTimeField(verbose_name='Сделать до')),
                ('status', models.CharField(choices=[('success', 'Выполнено'), ('process', 'В процессе')], default='process', max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.Events', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.AlterIndexTogether(
            name='events',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='tasks',
            index_together={('id', 'slug')},
        ),
    ]
