# Generated by Django 2.0.5 on 2018-12-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='event',
        ),
        migrations.AddField(
            model_name='events',
            name='event',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.Tasks', verbose_name='Событие'),
            preserve_default=False,
        ),
    ]
