# Generated by Django 2.0.5 on 2018-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='main',
            name='image',
            field=models.ImageField(upload_to='main/static/images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='main',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование:'),
        ),
    ]
