# Generated by Django 2.0.5 on 2018-11-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181108_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='main',
            name='slug',
            field=models.SlugField(default='bla-bla', unique=True, verbose_name='Адрес на сайте:'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='main',
            index_together={('id', 'slug')},
        ),
    ]
