# Generated by Django 2.0.5 on 2018-12-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user_id',
        ),
    ]
