# Generated by Django 2.0.5 on 2018-12-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_tasks_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Адрес'),
        ),
    ]
