# Generated by Django 2.0.5 on 2018-12-24 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181224_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created',
            field=models.DateField(default=datetime.date(2018, 12, 24), verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='term',
            field=models.DateTimeField(default=datetime.date(2018, 12, 24), verbose_name='Сделать до'),
        ),
    ]
