# Generated by Django 2.0.5 on 2018-12-24 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181224_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('success', 'Выполнено'), ('process', 'В процессе')], default='process', max_length=200, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='term',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 18, 48, 34, 907680), verbose_name='Сделать до'),
        ),
        migrations.AlterIndexTogether(
            name='events',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='events',
            name='slug',
        ),
    ]
